import type { AiAtomicDiffReviewInput } from '../../types.js';

export function createAtomicDiffReviewPrompt(
  input: AiAtomicDiffReviewInput,
): string {
  return [
    '你是代码审查助手。请把给定的一轮 AI 修改 diff 拆分成 N 个原子能力。',
    '',
    '原子能力类型必须使用以下编号：',
    '0: 格式调整',
    '1: 重构，包括重命名、拆分函数、移动代码位置等',
    '2: 新功能，包括新加一个函数、新加一个类',
    '3: 局部修复，包括修正局部逻辑、补齐边界处理、调整错误处理或修复局部集成问题',
    '5: 测试修改，包括新增测试、修改测试断言、调整测试夹具或测试快照',
    '',
    '拆分规则：',
    '1. 按照从底向上的 review 顺序排列：先基础类型、常量、工具函数和底层数据转换，再核心业务函数、类或接口，再调用点、展示层和测试。',
    '2. 每个原子能力必须只表达一个可独立理解的修改意图。',
    '3. 新功能可以作为原子能力类型，但必须继续拆小：每个新增函数、类、接口、数据结构或独立调用链尽量单独成项，避免把多个新功能混在同一个 item。',
    '4. 每个原子能力的规模必须足够小，便于人类轻松 review；如果一个 item 同时包含多个可独立检查的函数、类、接口或调用链，应继续拆分。',
    '5. 每个原子能力都必须包含该能力对应的 unified diff 片段。diff 可以裁剪上下文，但必须保留 diff --git、---、+++、@@ 以及相关增删行。',
    '6. 对每个原子能力解释修改意图，说明为什么做这个修改，而不是只复述改了哪些行。',
    '7. 如果原子能力涉及函数，intent 必须说明该函数的输入、输出和关键边界条件。',
    '8. 如果原子能力涉及类或接口，intent 必须说明该类或接口的作用，并逐一概括不同 method 的功能。',
    '9. 只基于输入材料，不要编造文件或行为。',
    '10. 只输出 JSON，不要输出 Markdown、代码围栏或额外解释。',
    '',
    '输出 JSON schema：',
    '{',
    '  "items": [',
    '    {',
    '      "id": "atomic-1",',
    '      "order": 1,',
    '      "capabilityType": 2,',
    '      "capabilityLabel": "新功能",',
    '      "title": "短标题",',
    '      "intent": "修改意图说明",',
    '      "files": ["path/to/file"],',
    '      "diff": "unified diff text",',
    '      "outputJson": {',
    '        "id": "atomic-1",',
    '        "order": 1,',
    '        "capability_type": 2,',
    '        "capability_label": "新功能",',
    '        "title": "短标题",',
    '        "intent": "修改意图说明",',
    '        "files": ["path/to/file"]',
    '      }',
    '    }',
    '  ]',
    '}',
    '',
    `原始 session id：${input.originalSessionId}`,
    `轮次：${input.round}`,
    '',
    '<SESSION_INPUT>',
    input.sessionInput,
    '</SESSION_INPUT>',
    '',
    '<EXECUTION_TRACE>',
    input.executionTrace || '无',
    '</EXECUTION_TRACE>',
    '',
    '<ASSISTANT_OUTPUT>',
    input.assistantOutput || '无',
    '</ASSISTANT_OUTPUT>',
    '',
    '<DIFF>',
    input.diff || '无',
    '</DIFF>',
  ].join('\n');
}
