import type { AiAtomicDiffReviewInput } from '../../types.js';

export function createAtomicDiffReviewPrompt(
  input: AiAtomicDiffReviewInput,
): string {
  return [
    '你是代码审查助手。请把给定的一轮 AI 修改 diff 拆分成 N 个原子能力。',
    '',
    '原子能力类型必须使用以下编号：',
    '0: 格式调整',
    '1: 重构，包括重命名、拆分函数、移动代码位置等',
    '2: 新功能，包括新加一个函数、新加一个类',
    '3: 单点修改，例如修改函数局部逻辑',
    '4: 多点调整，例如函数修改签名，导致所有上下游都需要跟着变化',
    '5: 测试修改，包括新增测试、修改测试断言、调整测试夹具或测试快照',
    '',
    '拆分规则：',
    '1. 按照人类 review 代码时的理解顺序排列，从结构入口、数据模型、核心逻辑、调用点、展示或测试逐步展开。',
    '2. 每个原子能力必须只表达一个可独立理解的修改意图。',
    '3. 每个原子能力都必须包含该能力对应的 unified diff 片段。diff 可以裁剪上下文，但必须保留 diff --git、---、+++、@@ 以及相关增删行。',
    '4. 对每个原子能力解释修改意图，说明为什么做这个修改，而不是只复述改了哪些行。',
    '5. 只基于输入材料，不要编造文件或行为。',
    '6. 只输出 JSON，不要输出 Markdown、代码围栏或额外解释。',
    '',
    '输出 JSON schema：',
    '{',
    '  "items": [',
    '    {',
    '      "id": "atomic-1",',
    '      "order": 1,',
    '      "capabilityType": 2,',
    '      "capabilityLabel": "新功能",',
    '      "title": "短标题",',
    '      "intent": "修改意图说明",',
    '      "files": ["path/to/file"],',
    '      "diff": "unified diff text",',
    '      "outputJson": {',
    '        "id": "atomic-1",',
    '        "order": 1,',
    '        "capability_type": 2,',
    '        "capability_label": "新功能",',
    '        "title": "短标题",',
    '        "intent": "修改意图说明",',
    '        "files": ["path/to/file"]',
    '      }',
    '    }',
    '  ]',
    '}',
    '',
    `原始 session id：${input.originalSessionId}`,
    `轮次：${input.round}`,
    '',
    '<SESSION_INPUT>',
    input.sessionInput,
    '</SESSION_INPUT>',
    '',
    '<EXECUTION_TRACE>',
    input.executionTrace || '无',
    '</EXECUTION_TRACE>',
    '',
    '<ASSISTANT_OUTPUT>',
    input.assistantOutput || '无',
    '</ASSISTANT_OUTPUT>',
    '',
    '<DIFF>',
    input.diff || '无',
    '</DIFF>',
  ].join('\n');
}
